RandomForestClassifier:
  oob_score: True
  n_estimators: 100
  min_samples_split: 2
  min_samples_leaf: 1
  max_samples: 0.75
  max_leaf_nodes: 2
  max_depth: 2
  max_features: 'sqrt'
  class_weight: 'balanced'
  random_state: 42